### ISSUE TITLE
Customize `async_result` trait

### ISSUE THREAD

**Issue by vinipsmaker** [jamboree/act#2]
Why the trouble of redefining every function of ASIO here (`act::read_some`, `act::write`, `act::accept`)? It's a dead-end, unless you expect to also reimplement every function of every library built on top ASIO ever (e.g. Boost.Beast).

**Comment by jamboree** [comment]
Unfortunately, it's impossible to implement them on top of `async_result` (w/o unnecessary overhead).
You can of course use something like what [p0286](http://wg21.link/p0286) did, but it's a much heavy-weight approach compared to simple wrappers in `act`.
